version: "3.2"
services:
  app:
    build:
      context: .
    container_name: app_atvd_complement
    restart: always
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default
    environment:
      - CI_ENV=development
    ports:
      - 8550:80
    # network_mode: "host"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres_db
  postgres_db:
    image: postgres
    container_name: postgres_db
    volumes:
      - db-atvd-complement:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: atvd_complement
    ports:
      # - 5432:5432
      - 8551:5432
volumes:
  db-atvd-complement:
    external: true